#define AUTO_SHIFT_REPEAT
#define CAPS_WORD_INVERT_ON_SHIFT
#define LSPO_KEYS KC_LEFT_SHIFT, KC_TRNS, KC_NUHS
#define LCPO_KEYS KC_LEFT_SHIFT, KC_TRNS, KC_NUBS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
